-- Chrome extension async challenges + notifications (docs/ARCHITECTURE.md "Chrome
-- extension design"). Same server-side-writes-only pattern as gameplay.sql for anything
-- score- or system-generated.

create table public.challenges (
  id                uuid primary key default gen_random_uuid(),
  quiz_id           uuid not null references public.quizzes(id),
  challenger_id     uuid not null references public.users(id),
  challenger_score  int,
  opponent_id       uuid not null references public.users(id),
  opponent_score    int,
  status            text not null default 'pending'
                      check (status in ('pending','opponent_played','completed','expired')),
  created_at        timestamptz not null default now(),
  expires_at        timestamptz not null
);

alter table public.challenges enable row level security;

create policy "challenges_select_participant" on public.challenges
  for select using (auth.uid() = challenger_id or auth.uid() = opponent_id);

create policy "challenges_insert_challenger" on public.challenges
  for insert with check (auth.uid() = challenger_id and challenger_id <> opponent_id);

-- No client UPDATE policy: challenger_score/opponent_score are written by the
-- server-side API route only, after it independently verifies a completed play —
-- a player can never write their own or their opponent's score directly.


create table public.notifications (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id),
  type          text not null check (type in ('challenge_received','challenge_result','streak_reminder','scheduled_quiz')),
  payload       jsonb not null,
  read_at       timestamptz,
  created_at    timestamptz not null default now()
);

alter table public.notifications enable row level security;

create policy "notifications_select_own" on public.notifications
  for select using (user_id = auth.uid());

create policy "notifications_update_own_read" on public.notifications
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- No client INSERT policy: notifications are always system-generated by the
-- server (service role) in response to a challenge, streak event, or scheduled quiz.
